#!/usr/bin/env bash
# Create RaccoonUI desktop shortcut on macOS / Linux.
# - macOS: ~/Desktop/RaccoonUI.app (proper bundle so Spotlight / Launchpad /
#   Finder show the raccoonui icon; legacy ~/Desktop/RaccoonUI.command is
#   removed if present so users get the upgraded entry on next install/update)
# - Linux: ~/Desktop/RaccoonUI.desktop (XDG entry)
# Invoked by install.sh; can also be run standalone.

set -euo pipefail

case "${OSTYPE:-}" in
    msys*|cygwin*|win32)
        printf "❌ 這個 script 是 macOS / Linux 用的。Windows 請跑 make-shortcut.ps1\n"
        exit 1
        ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RACCOONUI_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ ! -f "$SCRIPT_DIR/start.sh" ]; then
    printf "❌ start.sh 不存在: %s/start.sh\n" "$SCRIPT_DIR"
    printf "   先跑 install.sh 確保 scripts/raccoonui/ 完整\n"
    exit 1
fi

DESKTOP="$HOME/Desktop"
mkdir -p "$DESKTOP"

if [[ "$OSTYPE" == "darwin"* ]]; then
    APP_BUNDLE="$DESKTOP/RaccoonUI.app"
    LEGACY_COMMAND="$DESKTOP/RaccoonUI.command"
    ICNS_SRC="$RACCOONUI_DIR/assets/raccoonui.icns"

    # Migration: clean up legacy .command entry from earlier installs.
    if [ -f "$LEGACY_COMMAND" ]; then
        rm -f "$LEGACY_COMMAND"
    fi

    # Wipe any previous .app — re-stamp from scratch is cheap and avoids
    # stale Info.plist / icon caching weirdness.
    rm -rf "$APP_BUNDLE"
    mkdir -p "$APP_BUNDLE/Contents/MacOS"
    mkdir -p "$APP_BUNDLE/Contents/Resources"

    # Copy icon if available; .app still works without it (falls back to
    # generic app icon) but Spotlight/Launchpad won't show raccoonui logo.
    if [ -f "$ICNS_SRC" ]; then
        cp "$ICNS_SRC" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
    fi

    # Info.plist — bundle metadata that macOS reads for icon, name, version,
    # min OS, etc. CFBundleIconFile name must match Resources/AppIcon.icns
    # (without the .icns extension).
    cat > "$APP_BUNDLE/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>RaccoonUI</string>
    <key>CFBundleDisplayName</key>
    <string>RaccoonUI</string>
    <key>CFBundleIdentifier</key>
    <string>ai.raccoonai.raccoonui</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleExecutable</key>
    <string>RaccoonUI</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
</dict>
</plist>
PLIST

    # Launcher — bash script that opens Terminal.app and runs start.sh.
    # Using osascript so the user gets a visible console with daemon logs
    # (matches Win/Linux behavior). First launch will trigger an "RaccoonUI
    # wants to control Terminal" automation permission dialog — user must
    # click Allow once.
    cat > "$APP_BUNDLE/Contents/MacOS/RaccoonUI" <<LAUNCHER
#!/usr/bin/env bash
# RaccoonUI .app launcher — auto-generated by make-shortcut.sh
RACCOONUI_DIR="$RACCOONUI_DIR"
START_SH="\$RACCOONUI_DIR/scripts/raccoonui/start.sh"

if [ ! -x "\$START_SH" ]; then
    osascript -e "display alert \"RaccoonUI\" message \"start.sh not found at \$START_SH — re-run install.sh\" as critical"
    exit 1
fi

osascript <<APPLESCRIPT
tell application "Terminal"
    activate
    do script "cd '\$RACCOONUI_DIR' && '\$START_SH'"
end tell
APPLESCRIPT
LAUNCHER
    chmod +x "$APP_BUNDLE/Contents/MacOS/RaccoonUI"

    # Strip macOS quarantine flag so Gatekeeper does not block on first
    # launch (we built this .app locally — there is no notarization to
    # verify anyway). Best-effort: harmless if attribute is absent.
    xattr -dr com.apple.quarantine "$APP_BUNDLE" 2>/dev/null || true

    # Force Finder / Dock / Launchpad to refresh icon cache for this bundle.
    touch "$APP_BUNDLE"

    printf "✅ Desktop shortcut: %s\n" "$APP_BUNDLE"
    printf "   雙擊「RaccoonUI」啟動 daemon + 開瀏覽器\n"
    printf "\n"
    printf "   首次雙擊行為:\n"
    printf "     1. macOS Gatekeeper 可能擋 → 右鍵 → 開啟 → 系統設定 → 仍要打開\n"
    printf "     2. 跳「RaccoonUI 想控制 Terminal」對話框 → 點允許 (一次性)\n"
    printf "     3. Terminal 開起 daemon → 自動開瀏覽器\n"
    if [ ! -f "$ICNS_SRC" ]; then
        printf "\n"
        printf "   ⚠️  assets/raccoonui.icns 不存在 — Spotlight/Launchpad 會用 generic icon\n"
    fi

elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    SHORTCUT="$DESKTOP/RaccoonUI.desktop"
    ICON="$RACCOONUI_DIR/assets/logo.svg"

    cat > "$SHORTCUT" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=RaccoonUI
GenericName=Design system picker
Comment=RaccoonAI internal design tool — local web app
Exec=$SCRIPT_DIR/start.sh
Path=$RACCOONUI_DIR
Terminal=true
Categories=Development;Graphics;
EOF

    if [ -f "$ICON" ]; then
        echo "Icon=$ICON" >> "$SHORTCUT"
    fi

    chmod +x "$SHORTCUT"

    # GNOME / KDE both honor +x .desktop on Desktop, but GNOME 3.36+ also
    # needs `gio set ... metadata::trusted true` to skip the "Untrusted
    # application launcher" prompt.
    if command -v gio >/dev/null 2>&1; then
        gio set "$SHORTCUT" metadata::trusted true 2>/dev/null || true
    fi

    printf "✅ Desktop shortcut: %s\n" "$SHORTCUT"
    printf "   雙擊「RaccoonUI」啟動 daemon + 開瀏覽器\n"
    if [ -f "$ICON" ]; then
        printf "   icon: %s\n" "$ICON"
    fi
fi
