#!/usr/bin/env bash
# Create RaccoonUI desktop shortcut on macOS / Linux.
# - macOS: ~/Desktop/RaccoonUI.command (executable bash, double-click runs)
# - Linux: ~/Desktop/RaccoonUI.desktop (XDG entry)
# Invoked by install.sh; can also be run standalone.

set -euo pipefail

case "${OSTYPE:-}" in
    msys*|cygwin*|win32)
        printf "❌ 這個 script 是 macOS / Linux 用的。Windows 請跑 make-shortcut.ps1\n"
        exit 1
        ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RACCOONUI_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ ! -f "$SCRIPT_DIR/start.sh" ]; then
    printf "❌ start.sh 不存在: %s/start.sh\n" "$SCRIPT_DIR"
    printf "   先跑 install.sh 確保 scripts/raccoonui/ 完整\n"
    exit 1
fi

DESKTOP="$HOME/Desktop"
mkdir -p "$DESKTOP"

if [[ "$OSTYPE" == "darwin"* ]]; then
    SHORTCUT="$DESKTOP/RaccoonUI.command"
    cat > "$SHORTCUT" <<EOF
#!/usr/bin/env bash
# RaccoonUI launcher — auto-generated by make-shortcut.sh
cd "$RACCOONUI_DIR"
exec "$SCRIPT_DIR/start.sh"
EOF
    chmod +x "$SHORTCUT"

    printf "✅ Desktop shortcut: %s\n" "$SHORTCUT"
    printf "   雙擊「RaccoonUI.command」啟動 daemon + 開瀏覽器\n"
    printf "\n"
    printf "   首次雙擊 macOS Gatekeeper 可能擋下 — 改右鍵 → 開啟 → 系統設定允許\n"
    printf "   之後直接雙擊就行\n"
    printf "\n"
    printf "   tip: 換 icon 用 assets/logo.svg(raccoonui 工具自家 logo)透過\n"
    printf "        Cmd+I → 拖圖到左上角小圖示替換\n"

elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    SHORTCUT="$DESKTOP/RaccoonUI.desktop"
    ICON="$RACCOONUI_DIR/assets/logo.svg"

    cat > "$SHORTCUT" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=RaccoonUI
GenericName=Design system picker
Comment=RaccoonAI internal design tool — local web app
Exec=$SCRIPT_DIR/start.sh
Path=$RACCOONUI_DIR
Terminal=true
Categories=Development;Graphics;
EOF

    if [ -f "$ICON" ]; then
        echo "Icon=$ICON" >> "$SHORTCUT"
    fi

    chmod +x "$SHORTCUT"

    # GNOME / KDE both honor +x .desktop on Desktop, but GNOME 3.36+ also
    # needs `gio set ... metadata::trusted true` to skip the "Untrusted
    # application launcher" prompt.
    if command -v gio >/dev/null 2>&1; then
        gio set "$SHORTCUT" metadata::trusted true 2>/dev/null || true
    fi

    printf "✅ Desktop shortcut: %s\n" "$SHORTCUT"
    printf "   雙擊「RaccoonUI」啟動 daemon + 開瀏覽器\n"
    if [ -f "$ICON" ]; then
        printf "   icon: %s\n" "$ICON"
    fi
fi
